--[[
--------------------------------------------------------------------------------
Copyright (C) 2026 Alaestor Weissman

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
--------------------------------------------------------------------------------
--]]
--[[{
    # libALCE

    **Alaestor's Cheat Engine Library**

    Intended to be used in the table's lua script, or parted out as needed.

    #### Naming Conventions

    - Parameters

    `maybe_` prequalified parameters are conditionally required depending on other parameters; these _should_ be clearly documented. `optional_` parameters may be left nil. `internal_` parameters are used during recursion or similarly non-user-facing behaviors. Parameters without a prefixed qualifier are mandatory.

    #### Code Style

    I'm terribly not sorry. I'm normally the kind of person who has a strict 78 column limit; the kind of person understand visual blocking and lines of attention and follows strict and consistent formatting guidelines to better improve readability and intuitability... But as an experiment, I've thrown aesthetics and common-sense to the wind for this project. I pitty anyone who dares attempt to read this code. Forget "human-readable"; the LLMs can barely make sense of it. It's truly hidious and undecipherable. I **hate** it, and therefor it's perfect.

    #### About Documentation

    This README.md file is generated by a python script which creates it from (non-standard, custom-schema) lua docstrings. With `nix` installed, you can use `nix run . -- ./alcelib.lua ./README.md` to refresh this documentation.

    ---

    ### ALCE Configuration

    Defaults:

    ```lua

    alce.cfg = {
        debug_print = false,
        warn_print = true,
        isAddress_nearNullBoundary = 0xFFFF,
        isAddress_userspaceBoundary32 = 0xBFFFFFFF, -- 3g split; set 0x7FFFFFFF for 2GB
        isAddress_userspaceBoundary64 = 0x00007FFFFFFFFFFF,
        isOffset_tooFarBoundary = 0x1000, -- by default, expect offsets to be < 4096 B
    }
    ```

    These global config options can be set from anywhere at any time. Some functions, such as `isAddress`, have optional parameter overrides.

    ---

--}]]


--- top-level / global "namespace" table for the library
alce = {
   -- behavior flags and configuration values
    cfg = {
        debug_print = false,
        warn_print = true,
        isAddress_nearNullBoundary = 0xFFFF,
        isAddress_userspaceBoundary32 = 0xBFFFFFFF, -- 3g split; set 0x7FFFFFFF for 2GB
        isAddress_userspaceBoundary64 = 0x00007FFFFFFFFFFF,
        isOffset_tooFarBoundary = 0x1000, -- by default, expect offsets to be < 4096 B
    },
}

----------------------
-----< PRINTERS ------
----------------------
--- # Printers

--- print a formatted table with an optional title ( shorthand: `alce.i()` )
function alce.inspect(optional_title, tbl)
    if type(optional_title) ~= 'string' then
        assert(tbl == nil, 'alce.inspect(): invalid arguments')
        tbl = optional_title
        optional_title = nil
    end
    print('[INSPECT] ' .. alce.fmt.table((optional_title and {[tostring(optional_title)] = tbl}) or tbl))
end
alce.i = alce.inspect

--- print a sorted array of the table's keys ( shorthand: `alce.ik()` )
function alce.inspectKeys(optional_title, tbl)
    if tbl == nil then
        if type(optional_title) == 'table' then
            tbl = optional_title
            optional_title = nil
        else error('alce.inspectKeys(): invalid argument(s)') end
    end
    local keys = {}
    for key,_ in pairs(tbl) do table.insert(keys, key) end
    table.sort(keys)
    print('[INSPECT] ' .. alce.fmt.table((optional_title and {[tostring(optional_title)] = keys}) or keys))
end
alce.ik = alce.inspectKeys

--- pretty-stringifies, concatenates, and prints input ( shorthand: `alce.pp()` )
function alce.prettyprint(...)
    local args = {...}
    local result = ""
    for i = 1, #args do
        local a = args[i]
        local t = type(a)
        if t == 'string' or t == 'number' then result = result .. tostring(a)
        else result = result .. alce.fmt.pretty(a) end
    end
    print(result)
end
alce.pp = alce.prettyprint

--- print message with source linenumber only if alce.cfg.debug_print is `true`
function alce.debug(...)
    local info = debug.getinfo(2, "Sl")
    if alce.cfg.debug_print then alce.prettyprint(string.format("[DEBUG] L%i: ", info.currentline), ...) end
end

--- print message with source linenumber only if alce.cfg.warn_print is `true`
function alce.warn(...)
    local info = debug.getinfo(2, "Sl")
    if alce.cfg.warn_print then alce.prettyprint(string.format('[WARN] L%i: ', info.currentline), ...) end
end
----------------------
----/> PRINTERS ------
----------------------



-----------------------
-----< Utilities ------
-----------------------
--- # Utilities
--- All of these `is...` typecheckers return boolean..


--- returns whether CE is attached to a valid process
function alce.isAttached()
    return process and readInteger(process) ~= 0
end

function alce.isInteger(value)
    return type(value) == 'number' and math.type(value) == 'integer'
end

function alce.isPositiveInteger(value)
    return type(value) == 'number' and math.type(value) == 'integer' and value > 0
end

function alce.isNonNegativeInteger(value)
    return type(value) == 'number' and math.type(value) == 'integer' and value >= 0
end

function alce.isFloat(value)
    return type(value) == 'number' and math.type(value) == 'float'
end

function alce.isNonNegativeFloat(value)
    return type(value) == 'number' and math.type(value) == 'float' and value >= 0.0
end

function alce.isFiniteNumber(value)
    return type(value) == 'number' and value == value and value ~= math.huge and value ~= -math.huge
end

function alce.isNonEmptyString(value)
    return type(value) == 'string' and value ~= ''
end

function alce.isNonBlankString(value)
    return type(value) == 'string' and string.find(value, '%S') ~= nil
end

function alce.isEmptyTable(value)
    return type(value) == 'table' and next(value) == nil
end

function alce.isNonEmptyTable(value)
    return type(value) == 'table' and next(value) ~= nil
end

function alce.isZeroEmptyOrNil(value)
    local t = type(value)
    return t == nil or (t == 'number' and value == 0) or alce.isEmptyTable(value) or (not alce.isNonBlankString(value))
end

function alce.isCallable(value)
    if type(value) == 'function' then return true end
    local mt = getmetatable(value)
    return mt ~= nil and type(mt.__call) == 'function'
end

function alce.isBetween(value, minimum, maximmum)
    return value > minimum and value < maximum
end

--- checks that the vlaue `isInteger` and within positive and negative `optional_tooFarBoundary` (or `alce.cfg.isOffset_tooFarBoundary`)
function alce.isSignedOffsetlike(value, optional_tooFarBoundary)
    local boundary = (optional_tooFarBoundary or alce.cfg.isOffset_tooFarBoundary)
    return alce.isInteger(value) and value > -boundary and value < boundary
end

--- checks that the value `isNonNegativeInteger` and less than `optional_tooFarBoundary` (or `alce.cfg.isOffset_tooFarBoundary`)
function alce.isOffsetlike(value, optional_tooFarBoundary)
    return alce.isNonNegativeInteger(value) and value < (optional_tooFarBoundary or alce.cfg.isOffset_tooFarBoundary)
end

--- checks that the value `isInteger` and greater than `optional_nearNullBoundary` (or `alce.cfg.isAddress_nearNullBoundary`) and less than `optional_userspaceBoundary` (or `alce.cfg.isAddress_userspaceBoundary`)
function alce.isAddresslike(value, optional_nearNullBoundary, optional_userspaceBoundary)
    return alce.isInteger(value) and  value > (optional_nearNullBoundary or alce.cfg.isAddress_nearNullBoundary) and value < (optional_userspaceBoundary or (targetIs64Bit() and alce.cfg.isAddress_userspaceBoundary64 or alce.cfg.isAddress_userspaceBoundary32))
end

function alce.hasFlag(flag, flags) --> boolean: equivalent  `(flags & flag) == flag`
    return (flags & flag) == flag
end

--- passthru assert with source line (checks positive, e.g. `assert(value)` or `assert(optional_checker(value))`)
function alce.check(value, optional_checker) --> the input value
    local info = debug.getinfo(2, "Sl")
    assert(optional_checker == nil or alce.isCallable(optional_checker), 'line ' .. tostring(info.currentline) .. ': alce.check: invalid argument: optional_checker not callable.')
    assert(optional_checker and optional_checker(value) or value, 'line ' .. tostring(info.currentline) .. ': alce.check( ' .. tostring(value) .. ' )')
    return value
end

--- passthru negation-assert with source line (checks negative, e.g. `assert(not value)` or `assert(not optional_checker(value))`)
function alce.ncheck(value, optional_checker) --> the input value
    local info = debug.getinfo(2, "Sl")
    assert(optional_checker == nil or alce.isCallable(optional_checker), 'line ' .. tostring(info.currentline) .. ': alce.check: invalid argument: optional_checker not callable.')
    assert(not (optional_checker and optional_checker(value) or value), 'line ' .. tostring(info.currentline) .. ': alce.ncheck( ' .. tostring(value) .. ' )')
    return value
end

--- Traverses a pointer chain by repeating safe readPointer calls: (pointer, offsets,...)
function alce.readPointerChain(pointer, ...) --> nil|address
    assert(alce.isAddresslike(pointer), 'alce.readPointerChain(): invalid argument: pointer')
    local currentPtr = readPointer(pointer)
    local offsets = {...}
    for _,offset in ipairs(offsets) do
        if not alce.isOffsetlike(offset) then alce.warn('alce.readPointerChain(): suspicious offset: ' .. tostring(offset)) end
        currentPtr = readPointer(currentPtr + offset)
        if not alce.isAddresslike(currentPtr) then
            alce.warn('alce.readPointerChain(): invalid address when trying to chain the following:\n' .. alce.fmt.table({pointer=pointer, offsets=offsets}))
            return nil
        end
    end
    return currentPtr
end

--- just readPointerChain but it asserts the resulting address isAddressLike
function alce.safeChain(pointer, ...) --> address
    local info = debug.getinfo(2, "Sl")
    local result = alce.readPointerChain(pointer, ...)
    assert(alce.isAddresslike(result), 'line ' .. tostring(info.currentline) .. ': alce.safeChain(): resulting pointer was invalid:\n' .. alce.fmt.table({pointer=pointer, offsets=offsets, result=result}))
    return result
end

function alce.enumerate(iterator, optional_startFrom) --> integer from optional_startFrom or 1 , result of `iterator()`
    assert(alce.isCallable(iterator), 'alce.enumerate(): invalid argument: iterator: ' .. tostring(iterator))
    assert(optional_startFrom == nil or type(optional_startFrom) == 'number', 'alce.enumerate(): invalid argument: optional_startFrom' .. (optional_startFrom))
    local count = optional_startFrom or 1
    return function()
        local value = iterator()
        if value == nil then return nil end
        count = count + 1
        return count-1, value
    end
end

--- Recursively nil's keys with empty tables
function alce.prune(tbl)
    if type(tbl) ~= "table" then return end
    for k, v in pairs(tbl) do
        if type(v) == "table" then
            alce.prune(v)
            if next(v) == nil then tbl[k] = nil end
        end
    end
end

function alce.keyFromValue(value, tbl) --> nil or the first key associated with a given value
    for k,v in pairs(tbl) do if v == value then return k end end
end

function alce.keysFromValue(value, tbl) --> nil or an array of all the keys associated with a given value
    local keys={}
    for k,v in pairs(tbl) do if v == value then table.insert(keys, k) end end
    table.sort(keys)
    return next(keys) and keys or nil
end

--- assigns k,v pairs `from`->`to`, silently overwriting any duplicate keys
function alce.unsafeExtend(to, from)
    for k,v in pairs(from) do to[k] = v end
end

--- assigns k,v pairs `from`->`to`, asserting that the `from` key doesn't already exist in `to`
function alce.extend(to, from)
    for k,v in pairs(from) do
        assert(not to[k], 'alce.safeExtend(): key already exists: ' .. tostring(k))
        to[k] = v
    end
end
-----------------------
----/> Utilities ------
-----------------------



------------------------
-----< Formatters ------
------------------------
--- # Formatters

alce.fmt = {}

function alce.fmt.titleCase(str) --> string: "title case" -> "Title Case"
    return str:gsub("(%a)([%w']*)", function(first, rest) return first:upper() .. rest:lower() end)
end

local function byte_to_bits(byte)
    local bits = {}
    for i = 7, 0, -1 do bits[#bits + 1] = (byte >> i) & 1 end
    return table.concat(bits)
end
function alce.fmt.binary(value, optional_useDouble, optional_useNativeEndian) --> string: `0b` prefixed big-endien binary string representation in groups of 8
    assert(type(value) == 'number', 'alce.fmt.binary(): expected number, got type: ' .. type(value))
    local endian = optional_useNativeEndian and '' or '>'
    local fmt = (math.type(value) == 'integer') and (endian .. 'j') or (endian .. (optional_useDouble and 'd' or 'f'))
    local bytes = string.pack(fmt, value)
    local t = {}
    for i = 1, #bytes do t[i] = byte_to_bits(string.byte(bytes, i)) end
    return '0b' .. table.concat(t, ' ')
end

local BYTE_TO_HEX = {}
for i = 0, 255 do BYTE_TO_HEX[i] = string.format("%02X", i) end
function alce.fmt.hex(value, optional_withPadding, optional_useNativeEndian) --> string: 0x prefixed hexadecimal string representation
    assert(type(value) == 'number', 'alce.fmt.hex(): expected number, got type: ' .. type(value))
    local endian = optional_useNativeEndian and '' or '>'
    local fmt = (math.type(value) == 'integer') and (endian .. 'j') or (endian .. 'd')
    local bytes = string.pack(fmt, value)
    local hex = {}
    for i = 1, #bytes do hex[i] = BYTE_TO_HEX[string.byte(bytes, i)] end
    local result = table.concat(hex)
    if optional_withPadding ~= true then
        result = result:gsub("^0+", "")
        if result == "" then result = "0" end
    end
    return '0x' .. result
end

function alce.fmt.address(value) --> `alce.fmt.hex(value, true, false)` padded to address length
    if not alce.isInteger(value) then return 'NaN: ' .. tostring(value) end
    local full = alce.fmt.hex(value, true, false)
    if targetIs64Bit() then return full
    else return '0x' .. full:sub(-8) end
end

function alce.fmt.sanitizeSymbolName(str) --> string: the input string with non-alphanumeric replaced with underscores
    return string.gsub(str, '[^%a%d]', '_')
end

function alce.fmt.pretty(value, optional_printFullTable) --> string: single line, unless value is a table and optional_printFullTable is true.
    local t = type(value)
    if t == 'table' and optional_printFullTable then return alce.fmt.table(value)
    elseif t == 'string' then return '"' .. value .. '"'
    elseif t == 'number' then return string.format('%s  (%s: %s)', tostring(value), math.type(value), alce.fmt.hex(value))
    elseif t == 'function' or t == 'thread' or t == 'userdata' then return '<' .. tostring(value) .. '>'
    else return tostring(value) end
end

function alce.fmt.table(tbl, optional_depthLimit, optional_keysToIgnore, optional_dontToString, optional_dontSortKeys, internal_depth, internal_seen, internal_path) --> string: the human-readable representation of the table
    local depth = internal_depth or 0
    local seen = internal_seen or {}
    local path = internal_path or "root"
    local keysToIgnore = optional_keysToIgnore or {}
    local dontToString = optional_dontToString == true
    if type(tbl) ~= "table" or optional_depthLimit == depth then return alce.fmt.pretty(tbl) end
    if seen[tbl] then return string.format("<circular reference to %s @ %s>", seen[tbl], tostring(tbl):gsub("table: ", "")) end
    seen[tbl] = path
    if not dontToString then
        local mt = getmetatable(tbl)
        if mt and type(mt.__tostring) == "function" then
            local ok, str = pcall(mt.__tostring, tbl)
            if ok then return str end
        end
    end
    local result = {}
    local prefix = string.rep("  ", depth)
    -- Collect keys, skipping ignored ones
    local keys = {}
    for k in pairs(tbl) do if not keysToIgnore[k] then table.insert(keys, k) end end
    -- Sort unless disabled
    if not dontSortKeys then
        table.sort(keys, function(a, b)
            local ta, tb = type(a), type(b)
            if ta == tb then return a < b end
            return ta < tb
        end)
    end
    for _, k in ipairs(keys) do
        local v = tbl[k]
        local key_str = (type(k) == "string") and k or "[" .. tostring(k) .. "]"
        local current_path = path .. "." .. key_str
        local line_prefix = prefix .. key_str .. " = "
        if type(v) ~= "table" then table.insert(result, line_prefix .. alce.fmt.pretty(v))
        else
            if seen[v] then table.insert(result, line_prefix .. string.format("<circular reference to %s @ %s>", seen[v], tostring(v):gsub("table: ", "")))
            elseif next(v) == nil then table.insert(result, line_prefix .. "{}")
            else
                table.insert(result, line_prefix .. "{")
                table.insert(result, alce.fmt.table(v, optional_depthLimit, keysToIgnore, dontSortKeys, useCustomToString, depth + 1, seen, current_path))
                table.insert(result, prefix .. "}")
            end
        end
    end
    return table.concat(result, "\n")
end
------------------------
----/> Formatters ------
------------------------



-----------------------------
-----< CE helpers ------
-----------------------------
--- # CE Helpers

--- **NOTE:** `vtUnicodeString` is currently unsupported, and not included in any of the tables.

--- ## Plumbing

--[[{
    Collection related to global constants defined in CE's `monoscript.lua`

    Groups:
    - `monotype`
    - `fieldAttribute`
    - `methodAttribute`

    Each group's dict contains the string `prefix` of the global constants, an array of `names` and a `nameLookup` dict of names keyed by their value.

    **Note:** For each name string, you can get its value by `_G[name]`. For some monoTypes, `monoscript.lua` provides C-style type names via `monoTypeToCStringLookup[name]`
--}]]
alce.monoscript = {}

-- declare groups
for _,v in pairs({
    {name = 'monotype', prefix = 'MONO_TYPE_'},
    {name = 'fieldAttribute', prefix = 'FIELD_ATTRIBUTE_'},
    {name = 'methodAttribute', prefix = 'METHOD_ATTRIBUTE_'}
}) do
    alce.monoscript[v.name] = {}
    local t = alce.monoscript[v.name]
    t.prefix = v.prefix
    t.prefixLen = string.len(t.prefix)
    t.names = {}
    t.nameLookup = {}
end

-- map globals to groups
for k, v in pairs(_G) do
    if type(k) == 'string' then
        for _,group in pairs(alce.monoscript) do
            if k:sub(1,group.prefixLen) == group.prefix then
                table.insert(group.names, k)
                group.nameLookup[v] = k
            end
        end
    end
end

-- sort name arrays alphabetically
for _,group in pairs(alce.monoscript) do table.sort(group.names) end

--- a table of various CE type helpers. They can be useful on their own, but they mainly exist to be utilized by the user-friendly `alce.vt.VTypeHelper` instances in `alce.T`
alce.vt = {}

--- array of fundamental type strings (e.g. string `'byte'`, `'dword'`, `'pointer'`)
alce.vt.basicTypeStrings = {
    --'unicodeString',
    'byte',
    'word',
    'dword',
    'qword',
    'single',
    'double',
    'pointer',
}

--- array of CE type strings (e.g. string `'vtByte'`, `'vtDword'`, `'vtPointer'`)
alce.vt.typeStrings = {}
for _,v in ipairs(alce.vt.basicTypeStrings) do table.insert(alce.vt.typeStrings, 'vt' .. v:sub(1,1):upper() .. v:sub(2)) end

--- dict mapping CE's vt types and their respective sizes in bytes (accounts for 32/64bit processes; no support for 16bit addressing)
alce.vt.size = {
    --[vtUnicodeString] = 1,
    [vtByte]          = 1,
    [vtWord]          = 2,
    [vtDword]         = 4,
    [vtQword]         = 8,
    [vtSingle]        = 4,
    [vtDouble]        = 8,
    [vtString]        = targetIs64Bit() and 8 or 4,
    [vtPointer]       = targetIs64Bit() and 8 or 4,
}

--- dict mapping CE's vt types and their respective read functions (e.g. `[vdDword]` is `readInteger`)
alce.vt.read = {
    --[vtUnicodeString] = readString, --? should this be readBytes looking nullterm? just niling for now
    [vtByte]          = function(addr) return readBytes(addr, 1, false) end,
    [vtWord]          = readSmallInteger,
    [vtDword]         = readInteger,
    [vtQword]         = readQword,
    [vtSingle]        = readFloat,
    [vtDouble]        = readDouble,
    [vtString]        = readString,
    [vtPointer]       = readPointer,
}

--- mapping of CE's vt types and their respective write functions (e.g. `[vdDword]` is `writeInteger`)
alce.vt.write = {
    --[vtUnicodeString] = writeString, --? see read
    [vtByte]          = function(addr, val) return writeBytes(addr, {val & 0xFF}) end,
    [vtWord]          = writeSmallInteger,
    [vtDword]         = writeInteger,
    [vtQword]         = writeQword,
    [vtSingle]        = writeFloat,
    [vtDouble]        = writeDouble,
    [vtString]        = writeString,
    [vtPointer]       = function(addr, val) return (targetIs64Bit() and writeQword or writeInteger)(addr, val) end,
}

--- for working with a vartype such as: finding its monotypes, reading and writing, and formatting invoke-style argument tables.
alce.vt.VTypeHelper = {
    new = function(self, basicTypeString) --> a newly created VType
        assert(alce.isNonBlankString(basicTypeString), 'alce.T.VType(): invalid argument: typeString: ' .. tostring(typeString))
        local vts = 'vt' .. basicTypeString:sub(1,1):upper() .. basicTypeString:sub(2)
        local vt = _G[vts]
        assert(alce.isInteger(vt), 'alce.T.VType(): invalid argument: basicTypeString: no global variable named ' .. tostring(vts) )
        local instance = {
            name = basicTypeString,
            vtName = vts,
            vType = vt,
            size = alce.vt.size[vt],
            readUnsafe = alce.vt.read[vt],
            writeUnsafe = alce.vt.write[vt],
        }
        setmetatable(instance, { __index = self, __call = self.asInvokeArgument, __name ='VTypeHelper: ' .. basicTypeString })
        return instance
    end,

    getMonotypes = function(self) --> nil or array of integers
        return alce.keysFromValue(self.vType, monoTypeToVartypeLookup)
    end,

    getMonotypesAsStrings = function(self) --> nil or a sorted array of strings representing the monotypes: *(note: use `monoTypeToCStringLookup[]` if you want basic type strings; but not all are represented)*
        local keys = alce.keysFromValue(self.vType, monoTypeToVartypeLookup)
        local r = {}
        for _,v in ipairs(keys) do table.insert(r, alce.monoscript.monotype.nameLookup[v]) end
        table.sort(r)
        return next(r) and r or nil
    end,

    asInvokeArgument = function(self, value) --> dict formatted for invoking methods e.g. `{type=, value=}`
        return {type = self.vType, value = value}
    end,

    read = function(self, address) --> nil or the value
        assert(self.readUnsafe, 'alce.T.VType.read(): no read function for type ' .. self.name)
        assert(alce.isAddresslike(address), 'alce.T.VType.read(): invalid address')
        return self.readUnsafe(address)
    end,

    write = function(self, address, value) --> boolean: whether or not it succeeded
        assert(self.writeUnsafe, 'alce.T.VType.write(): no write function for type ' .. self.name)
        assert(alce.isAddresslike(address), 'alce.T.VType.write(): invalid address')
        return self.writeUnsafe(address, value)
    end,
}

--- ## Porcelain

--[[{
    A convenient table that can be indexed by CE vartype value (`vtDword`), basic type string (`'dword'`), or CE vartype string (`'vtDword'`) to get a corresponding `alce.vt.VTypeHelper`. Useful for quick conversions, creating arguments, or doing type-appropriate reads/writes programmatically.

    Example usage:
    ```lua
    -- read and write values
    local x = alce.T[vtDword]:read(x_addr)
    alce.T[vtDword]:write(y_addr, x)

    -- easy conversions
    local t = alce.T.(something.type)
    print('The type is ' .. t.name) -- basic lowercase type name without the vartype `vt` prefix
    assert(alce.T[t.name] == alce.T[t.vType])
    print('That type is used for the following monotypes: ' .. alce.fmt.table(t:getMonotypes)) -- prints integer

    -- creating `{type=,value=}` dict pairs (calling is just a shorthand for `asInvokeArgument`)
    invoke(method, {
        alce.T[vtPointer]:asInvokeArgument(instance),
        alce.T[vtString]('my string'), -- lookup by vartype integer ID
        alce.T['single'](3.14159), -- lookup by basic type name
        alce.T['vtSingle'](6.28318) -- lookup by vartype string
    })
    ```
--}]]
alce.T = {}
for _,v in pairs(alce.vt.basicTypeStrings) do
    local t = alce.vt.VTypeHelper:new(v)
    for _,lookupKey in pairs({t.name, t.vtName, t.vType}) do
        assert(not alce.T[lookupKey], 'alce.T: key already exists: ' .. tostring(lookupKey))
        alce.T[lookupKey] = t
    end
end
-- find the max key
local alce_monotype_max_key = -math.huge
for k,_ in pairs(monoTypeToVartypeLookup) do if type(k) == 'number' and k > alce_monotype_max_key then alce_monotype_max_key = k end end

--- Equivalent to `alce.T[monoTypeToVarType(monoType)]` with warning message when it will fail and return the `vtDword` fallback.
function alce.T.unsafeFromMono(monoType) --> VTypeHelper
    if (not alce.isInteger(monoType)) or monoType > alce_monotype_max_key then alce.warn('alce.T.unsafeFromMono(): monoType (' .. tostring(monoType) .. ') is bigger than the largest monoTypeToVartypeLookup key. Monoscript defaults to vtDword.') end
    return alce.T[monoTypeToVarType(monoType)]
end
--- Equivalent to `alce.T[monoTypeToVartypeLookup[monoType]]` with a bounds-checking assertion; will not fallback to `vtDword`.
function alce.T.fromMono(monoType) --> VTypeHelper
    assert(alce.isInteger(monoType) and monoType <= alce_monotype_max_key, 'alce.T.fromMono(): monoType (' .. tostring(monoType) .. ') is bigger than the largest monoTypeToVartypeLookup key.')
    return alce.T[monoTypeToVartypeLookup[monoType]]
end

local function AllocateSymbols_register(context, optional_names)
    assert(optional_names == nil or type(optional_names) == 'table', 'alce.memory.AllocateSymbols.unregister(): invalid argument: optional_names must be an array of strings or nil.')
    local namesToRegister = optional_names or context.names
    for _, name in ipairs(namesToRegister) do
        assert(context.addresses[name], "alce.memory.AllocateSymbols.unregister(): invalid argument: invalid name: " .. tostring(name))
        if not context.registered[name] then
            local symbol = context.symbolNames[name]
            local address = context.addresses[name]
            registerSymbol(symbol, address, true)
            context.registered[name] = symbol
        end
    end
end

local function AllocateSymbols_unregister(context, optional_names)
    assert(optional_names == nil or type(optional_names) == 'table', 'alce.memory.AllocateSymbols.unregister(): invalid argument: optional_names must be an array of strings or nil.')
    local namesToUnregister = {}
    if optional_names == nil then for name, _ in pairs(context.registered) do table.insert(namesToUnregister, name) end
    else namesToUnregister = optional_names end
    for _, name in ipairs(namesToUnregister) do
        assert(context.registered[name], "alce.memory.AllocateSymbols.unregister(): invalid argument: symbol not registered: " .. tostring(name))
        local symbol = context.registered[name]
        unregisterSymbol(symbol)
        context.registered[name] = nil
    end
end

--[[{
    Allocates contiguous memory aliased by name calculated by type size and provides easy read/write access to them. Also lets you register/unregister the names as global symbols with an optional prefix.

    > **Note:** the registered symbols will have all non-alphanumeric characters replaced with underscores. Symbols will be registered by default at creation unless you the optional parameter `doNotRegister` is true.

    Optional parameters: `doNotRegister` boolean, `symbolPrefix` string, and `baseAddress` which would be forwarded to `allocateMemory`.

    Exposes methods `register(optional_names)` and `unregister(optional_names)`. `optional_names` may be nil or an array of valid and unprefixed names. If nil, the functions perform the action for all symbols for all symbols not already registered/unregistered.

    The object also exposes internal state through __ prefixed keys. You probably shouldn't write to these but I'm a line of documentation, not a cop.
    - `__size` - the total size of the memory region in bytes.
    - `__memory` - base address of the memory region.
    - `__names` - array of names as they would be accessed for reading/writing.
    - `__symbolPrefix` - the string to be prefixed to names when registering and unregistering symbols.
    - `__symbolNames` - dict of names to (optionally-prefixed) symbol names as they would be globally registered.
    - `__addresses` - dict of name keys to integer addresses in the memory region.
    - `__types` - dict of name string keys to alce.vt.VTypeHelper objects.
    - `__registered` - dict of names to registered symbolnames; presense in table means that the symbols are registered.

    Example usage:
    ```lua
    -- this is important, and it should be global to persist state.
    region = region or MemoryRegion({
        alce.T[vtDword]('level'), -- or { type = vtDword, name = 'level' },
        alce.T[vtSingle]('health'),
      },{ -- optionals
        doNotRegister = true,
        symbolPrefix = 'PTR_'
    })
    [ENABLE]
    -- write to aliased memory by using the unprefixed names
    region.level = 99
    region.health = 100.0
    assert(region:register(), 'failed: already registered?') -- manually, since we set `doNotRegister`

    -- access the registered CE symbols from anywhere
    print(string.format('health is stored at address: 0x%X', PTR_health))

    -- get type information from an internal table (VTypeHelper)
    print('level is a ' .. region.__types['health'].name)

    [DISABLE]
    -- read from aliased memory
    print('ending health: ', region.health)
    region:unregister()
    ```
--}]]
function alce.AllocateSymbols(packets, optional) --> proxy object
    assert(alce.isNonEmptyTable(packets), 'alce.memory.AllocateSymbols(): invalid argument: packets must be a non-empty table')
    assert(optional == nil or alce.isNonEmptyTable(optional), 'alce.memory.AllocateSymbols(): invalid argument: optional must be nil or a non-empty table')
    assert(optional == nil or optional.symbolPrefix == nil or alce.isNonBlankString(optional.symbolPrefix), 'alce.memory.AllocateSymbols(): invalid argument: optional.symbolPrefix must be nil or a non-blank string')
    assert(optional == nil or optional.baseAddress == nil or alce.isAddresslike(optional.baseAddress), 'alce.memory.AllocateSymbols(): invalid argument: optional.baseAddress must be nil or addresslike')
    assert(optional == nil or optional.protection == nil or type(optional.protection) == 'boolean', 'alce.memory.AllocateSymbols(): invalid argument: optional.protection must be nil or a boolean value')
    local doNotReigster = optional and optional.doNotRegister == true or false
    local internal = {
        size = 0,
        memory = nil,
        names = {},
        symbolPrefix = optional and optional.symbolPrefix or '',
        symbolNames = {},
        addresses = {},
        types = {},
        registered = {},
    }
    for i, packet in ipairs(packets) do
        assert(alce.isNonEmptyTable(packet), 'alce.memory.AllocateSymbols(): invalid argument: packets[' .. tostring(i) .. '] must be a table of {type=,value=}')
        local name = packet.value
        assert(alce.isNonBlankString(name), 'alce.memory.AllocateSymbols(): invalid argument: packets[' .. tostring(i) .. '] name must be a non-blank string')
        table.insert(internal.names, name)
        local t = alce.T[packet.type]
        assert(t, 'alce.memory.AllocateSymbols(): invalid argument: packets[' .. tostring(i) .. '] type must be a key compatible with alce.T (e.g. a CE vartype like `vtSingle`)')
        internal.types[name] = t
        internal.symbolNames[name] = alce.fmt.sanitizeSymbolName(internal.symbolPrefix .. name)
        internal.size = internal.size + t.size
    end
    internal.memory = allocateMemory(internal.size, optional and optional.baseAddress or nil)
    assert(alce.isAddresslike(internal.memory), 'alce.memory.AllocateSymbols(): failed to allocate memory...')
    local cursor = internal.memory
    for _,name in ipairs(internal.names) do
        internal.addresses[name] = cursor
        cursor = cursor + internal.types[name].size
    end
    if not doNotReigster then AllocateSymbols_register(internal) end

    local proxy = {}
    setmetatable(proxy, {
        __name = 'AllocateSymbolsProxy: ' .. alce.fmt.address(internal.memory),

        __pairs = function(_) error("alce.memory.AllocateSymbols.__pairs(): doesn't support iteration") end,

        __eq = function(a, b)
            local ameta = getmetatable(a)
            local bmeta = getmetatable(b)
            return ameta == bmeta and rawequal(ameta.__index, bmeta.__index)
        end,

        -- __index handles reads and internal access
        __index = function(tbl, key)
            if key:sub(1, 2) == "__" then return internal[key:sub(3)]
            elseif key == 'register' then return function(optional_self, ...) -- self is unnecessary: workaround to allow both `:` and `.` calling
                    if optional_self == tbl then return AllocateSymbols_register(internal, ...)
                    else return AllocateSymbols_register(internal, optional_self, ...) end
                end
            elseif key == 'unregister' then return function(optional_self, ...) -- self is unnecessary: workaround to allow both `:` and `.` calling
                    if optional_self == tbl then return AllocateSymbols_unregister(internal, ...)
                    else return AllocateSymbols_unregister(internal, optional_self, ...) end
                end
            else
                local t = internal.types[key]
                assert(t, "alce.memory.AllocateSymbols.__index(): couldn't find type for key: " .. tostring(key))
                local a = internal.addresses[key]
                assert(a, "alce.memory.AllocateSymbols.__index(): couldn't find address for key: " .. tostring(key))
                return t:read(a)
            end
        end,

        -- __newindex handles writes
        __newindex = function(_, key, value)
            local t = internal.types[key]
            assert(t, "alce.memory.AllocateSymbols.__newindex(): couldn't find type for key: " .. tostring(key))
            local a = internal.addresses[key]
            assert(a, "alce.memory.AllocateSymbols.__newindex(): couldn't find address for key: " .. tostring(key))
            return t:write(a, value)
        end,
    })
    return proxy
end
-----------------------------
----/> CE type helpers ------
-----------------------------



---------------------------
-----< Mono Features ------
---------------------------
--- # Mono Features

alce.mono = {}

--- ## Plumbing

--[[{
    Dumbed-down mono_invoke_method with a bugfix for [cheat-engine issues 3350](https://github.com/cheat-engine/cheat-engine/issues/3350)

    `maybe_arguments` may be omitted if method takes none. `maybe_instance` may be omitted if method is static. `optional_` parameters simply help to avoid redundant calls if you already have them.
--}]]
function alce.mono.invoke(methodID, maybe_instance, maybe_arguments, optional_parameters, optional_flags) --> any|nil,string|nil,string|nil?: result, exception, vtype; identical to `mono_invoke_method`
  alce.debug('alce.mono.invoke(): invoke_method called')
  assert(alce.isPositiveInteger(methodID), 'alce.mono.invoke(): invalid argument: methodID: '..tostring(methodID))

  local static=((optional_flags or mono_method_getFlags(methodID)) & METHOD_ATTRIBUTE_STATIC) == METHOD_ATTRIBUTE_STATIC
  assert(alce.isAddresslike(maybe_instance) or static, 'alce.mono.invoke(): invalid argument: maybe_instance is required for non-static methods')

  local argument_count = #maybe_arguments
  local params = optional_parameters or mono_method_get_parameters(methodID)
  assert(argument_count == #params, 'alce.mono.invoke(): invalid argument: length of maybe_arguments does not match method parameters')
  for _,arg in ipairs(maybe_arguments) do
    assert(type(arg) == 'table' and arg.type and arg.value ~= nil, 'alce.mono.invoke(): invalid argument: maybe_arguments not well-formed')
  end

  local object=maybe_instance
  if object and object~=0 then
    local class=mono_method_getClass(methodID)
    if mono_type_get_type(mono_class_get_type(class))==MONO_TYPE_VALUETYPE then
      --the object needs to be unboxed to be able to be used
      object=mono_object_unbox(object)
    end
  end

  local result, vtype, exception
  local r,err=pcall(function()
    assert(mono_isValid(), 'alce.mono.invoke(): invalid mono state. Mono features not active?')
    alce.debug('alce.mono.invoke(): invoking MONOCMD_INVOKEMETHOD')
    libmono.monopipe.writeByte(MONOCMD_INVOKEMETHOD)
    libmono.monopipe.writeQword(methodID)
    libmono.monopipe.writeQword(object or 0)
    for i=1, argument_count do
      mono_writeObject(maybe_arguments[i].type, maybe_arguments[i].value)
    end

    alce.debug('alce.mono.invoke(): waiting for result')
    result, vtype = mono_readObject()
    alce.debug('alce.mono.invoke(): result='..tostring(result)..' vtype='..tostring(vtype))
    if libmono.monopipe.readByte() == 1 then
      if libmono.monopipe.readByte() == 1 then
        local excplen = libmono.monopipe.readWord()
        exception = libmono.monopipe.readString(excplen)
      end
    end

    if vtype==MONO_TYPE_VALUETYPE then
      --read the fields from this type and return that instead
      local f=mono_object_enumValues(result)
      if f then
        result=f
        return f, exception, vtype
      end
    end
  end)
  if r then
    return result, exception, vtype
  else
    return nil, err
  end
end

--- Expects `array` to be the result from either `mono_class_enumMethods` or `mono_class_enumFields`, and `hierarchy` to be the result from `alce.mono.class_getParentHierarchy`
function alce.mono.sortByHierarchy(array, hierarchy) --> array: sorted by parent hierarchy, from parent to child
    assert(alce.isNonEmptyTable(hierarchy), 'alce.mono.sortByHierarchy(): invalid argument: hierarchy is expected to be the result of alce.mono.class_getParentHierarchy.')
    if not array then return nil end
    local ClassID = hierarchy[#hierarchy]
    local classOrder = {}
    for i, classId in ipairs(hierarchy) do classOrder[classId] = i end
    table.sort(array, function(a, b)
        local orderA = classOrder[a.parent or ClassID]
        local orderB = classOrder[b.parent or ClassID]
        if orderA ~= orderB then return orderA < orderB end
        if a.name ~= b.name then return a.name < b.name end
        return (a.field or a.method) < (b.field or b.method) -- tiebreaker
    end)
    return array
end

--- Helper function to get Image by assemblyName (e.g. `Assembly-CSharp`)
function alce.mono.getImage(assemblyName, optional_enumeratedAssemblies) --> nil | integer: image handle
    assert(optional_enumeratedAssemblies == nil or alce.isNonEmptyTable(optional_enumeratedAssemblies), 'alce.mono.getImage(): invalid argument: alce.mono.getImage')
    local assemblies = optional_enumeratedAssemblies or mono_enumAssemblies()
    assert(alce.isNonEmptyTable(assemblies), "alce.mono.getImage(): Couldn't enumerate assemblies. Mono features not active?")
    for _, assembly in ipairs(assemblies) do
        local image = mono_getImageFromAssembly(assembly)
        if image and mono_image_get_name(image) == assemblyName then return image end
    end
    alce.warn("alce.mono.getImage(): Failed to find " .. tostring(assemblyName))
    return nil
end

--- Helper to find a class by name in a specific assembly and namespace
function alce.mono.getClassEx(assemblyNameOrImage, className, optional_namespace) --> dict: { Name, Handle, NestingTypeHandle, FullName, NameSpace, ParentHandle }
    assert(alce.isPositiveInteger(assemblyNameOrImage) or alce.isNonBlankString(assemblyNameOrImage), 'alce.mono.getClassEx(): invalid argument: assemblyNameOrImage: ' .. tostring(assemblyNameOrImage))
    assert(alce.isNonBlankString(className), 'alce.mono.getClassEx(): invalid argument: className')
    assert(optional_namespace == nil or type(optional_namespace) == 'string', 'alce.mono.getClassEx(): invalid argument: optional_namespace')
    local t = type(assemblyNameOrImage)
    local image = t == 'number' and assemblyNameOrImage or t == 'string' and alce.mono.getImage(assemblyName) or nil
    assert(image, "alce.mono.getClassEx(): Failed to get image: '" .. tostring(assemblyName) .. "'")
    for _,v in ipairs(mono_image_enumClassesEx(image)) do if v.FullName == className and (optional_namespace and optional_namespace == v.NameSpace or true) then return v end end
    alce.warn("alce.mono.getClassEx(): No results  for getClassEx(" .. tostring(assemblyNameOrImage)..", " .. className .. ((optional_namespace and ', ""'..optional_namespace..'"') or '') .. ")")
    return nil
end

function alce.mono.getClass(assemblyNameOrImage, className, optional_namespace) --> nil | integer: class handle
    local r = alce.mono.getClassEx(assemblyNameOrImage, className, optional_namespace)
    return r and r.Handle or nil
end

function alce.mono.method_getSignature(methodID, optional_methodName) --> dict: of strings{paramtypes, paramnames, returntype, initials, full}
    assert(alce.isPositiveInteger(methodID), 'alce.mono.method_getSignature(): invalid argument: methodID')
    local name = alce.isNonBlankString(optional_methodName) and optional_methodName or mono_method_getName(methodID)
    local paramtypes_raw, paramnames, returntype = mono_method_getSignature(methodID)
    local paramtypes = string.gsub(paramtypes_raw, '/', '+') -- normalize nested typenames to be consistent...
    local t = { types = paramtypes, paramnames = paramnames, returntype = returntype }
    t.initials = string.format('%s(%s)', name, paramtypes or '')
    local typenames=mono_splitParameters(paramtypes)
    local params = ''
    if typenames and #typenames == #paramnames then
        local rr={}
        for i=1, #typenames do rr[i] = typenames[i] .. ' ' .. paramnames[i] end
        params = table.concat(rr, ",")
    end
    local front = string.gsub(string.match(mono_method_getFullName(methodID), "^(.-) %("), '/', '+') -- chop off params and normalize
    t.full = string.format('%s(%s)', front, params)
    return t
end

function alce.mono.class_getParentHierarchy(classID) --> array of class IDs ordered from parent to child (with classID being last)
    assert(alce.isPositiveInteger(classID), 'alce.mono.class_getParentHierarchy(): invalid argument: classID: ' .. tostring(classid))
    local hierarchy = {}
    local current_class = classID
    while current_class and current_class ~= 0 do
        table.insert(hierarchy, 1, current_class)
        current_class = mono_class_getParent(current_class)
    end
    return hierarchy
end

--[[{
    Returns type-categorized value and metadata subtables keyed by field name.

    - `static` a dict of name-keyed static addresses.

    - `offset` dict of name-keyed integer offsets.

    - `const` dict of name-keyed static-const value literals (such as enum values or other constants)

    - `constToKey` dict that's the inverse mapping of const: value to key (useful for quick string lookups)

    Also defines `startOffset` to be the lowest offset; either the result of `mono_structfields_getStartOffset(fields)` or `0x10` (64bit) / `0x8` (32bit) depending on target architecture. Note that this may not be the start of the object if parent's aren't included.

    If `optional_keepMetadata` is true, then the subtable `meta` will contain subtables `const`, `static`, and `offset`
    each of which are dicts with keys identical to the main tables, each of which will contain contain
    `typename`, `type`, `vtype`, `monotype`, and `flags` for their respective counterpart. e.g.
    `class.meta.offset.hp` holds the metadata for `class.offset.hp`. One thing to note is that `vtype` is the result of
    `monoTypeToVartypeLookup[monotype]` so it may be nil.

    If `optional_keepFields` is true, then the subtable `fields` will contain a reference to the raw enumerated fields.

    In cases of collision, the derived class field 'shadows' (overwrites) the base class field.
    To access a shadowed field, you'll need to get the fields of the parent separately.
    Collisions probably shouldn't occur unless `optional_getParents` is `true`.

    *Note: automatically removes `enumSeperator` and `enumSeparatorCharArray` from `const` value list*
--}]]
function alce.mono.getProcessedFields(classID, optional_getParents, optional_hierarchy, optional_keepMetadata, optional_keepFields) --> nil|dict: { static, const, offset, meta? = { const, static, offset }, fields? }
    local fields = mono_class_enumFields(classID, optional_getParents)
    if type(fields) ~= 'table' then
        alce.warn('alce.mono.getProcessedFields(): failed to lookup fields')
        return nil
    end
    if optional_getParents == true then
        assert(optional_hierarchy == nil or alce.isNonEmptyTable(optional_hierarchy), 'alce.mono.getProcessedFields(): Invalid argument: optional_hierarchy')
        fields = alce.mono.sortByHierarchy(fields, optional_hierarchy or alce.mono.class_getParentHierarchy(classID))
    end
    local startOffset = mono_structfields_getStartOffset(fields)
    if not startOffset then startOffset = targetIs64Bit() and 0x10 or 0x8 end
    local t = {
        startOffset = startOffset,
        const = {},
        static = {},
        offset = {},
        meta = optional_keepMetadata == true and {
            const = {},
            static = {},
            offset = {},
        } or nil,
        constToKey = {},
        fields = optional_keepFields == true and fields or nil,
    }
    local function warnIfCollides(subtable, f)
        if not t[subtable][f.name] then return nil end
        local dstr = ((not alce.cfg.debug_print and "Set 'alce.cfg.debug_print=true` for more information.")
            or string.format('\n[WARN-DEBUG]>\nReplacing...\n---\n%s\n---\nwith data from...\n---\n%s\n---\n',
                alce.fmt.table(t[subtable][f.name]), alce.fmt.table(f)))
        alce.debug(string.format("alce.mono.getProcessedFields(): duplicate %s field named '%s' detected. %s", subtable, f.name, dstr))
    end
    local function store(ts, f, val)
        warnIfCollides(ts, f)
        t[ts][f.name] = val
        if optional_keepMetadata == true then
            t.meta[ts][f.name] = {}
            local meta = t.meta[ts][f.name]
            for _,k in pairs({ 'typename', 'type', 'monotype', 'flags' }) do meta[k] = f[k] end
            meta.vtype = monoTypeToVartypeLookup[meta.monotype] or nil
        end
    end
    for _,f in pairs(fields) do
        if f.staticAddress then store('static', f, f.staticAddress)
        elseif f.isConst then store('const', f, mono_class_getStaticFieldValue(classID, f.field))
        elseif f.offset then store('offset', f, f.offset)
        else alce.warn("alce.mono.getProcessedFields(): uncategorized field; what is this?\n??:" .. alce.fmt.table(f)) end
    end
    -- get rid of some junk
    t.const.enumSeperator = nil
    t.static.enumSeparatorCharArray = nil
    if next(t.const) then for k,v in pairs(t.const) do t.constToKey[v] = k end end
    return t or nil
end

--[[{
    Returns a table of methods keyed by the function name (e.g. `SetHealth`) or initials (e.g. `SetHealth(single)`).
    Overloaded methods will have no short "name" key, and must be disambiguated by initials (which includes the parameter types).

    In cases of collision, the derived class method 'shadows' (overwrites) the base class method.
    To access a shadowed method, you'll need to get the methods of the parent separately.
--}]]
function alce.mono.getProcessedMethods(classID, optional_getParents, optional_hierarchy) --> nil|dict: { key = alce.mono.Method, ... }
    local methods = mono_class_enumMethods(classID, optional_getParents)
    if type(methods) ~= 'table'  then
        alce.warn('alce.mono.getProcessedMethods(): Failed to enumerate methods')
        return nil
    end
    if optional_getParents == true then -- ensures we overwrite the right methods...
        assert(optional_hierarchy == nil or alce.isNonEmptyTable(optional_hierarchy), 'alce.mono.getProcessedMethods(): Invalid argument: optional_hierarchy')
        methods = alce.mono.sortByHierarchy(methods, optional_hierarchy or alce.mono.class_getParentHierarchy(classID))
    end
    local t={}
    for _,mpack in ipairs(methods) do
        local m = alce.mono.Method:new(mpack.method, mpack.name, mpack.flags)
        -- tombstone the shorthand if method is overloaded, but not if it's free or merely shadowing.
        if not t[mpack.name] or (t[m.signature.initials] and t[mpack.name] ~= 'tombstone') then t[mpack.name] = m
        else t[mpack.name] = 'tombstone' end
        t[m.signature.initials] = m
    end
    for k,_ in pairs(t) do if t[k] == 'tombstone' then t[k] = nil end end
    return t
end


--- ## Porcelain

--- helpers for commonly used mscorlib/system type offsets
alce.mono.T = {}

--- a friendly alias for mscorlib System.Collections.Generic.List types
alce.mono.T.List = {

    indexFrom = 0x20,
    indexBy = 0x8,
    offset = {
        items = 0x10,
        size = 0x18
    },

    new = function(self, baseAddress, optional_indexFrom, optional_indexBy, optional_offsetItems, optional_offsetSize) --> the newly created T.list that aliases `address`
        assert(alce.isAddresslike(baseAddress), 'alce.mono.T.List.new(): invalid argument: baseAddress: ' .. tostring(baseAddress))
        assert((not optional_indexFrom) or alce.isOffsetlike(optional_indexFrom), 'alce.mono.T.List.new(): invalid argument: optional_indexFrom')
        assert((not optional_indexBy) or alce.isOffsetlike(optional_indexBy), 'alce.mono.T.List.new(): invalid argument: optional_indexBy')
        assert((not optional_offsetItems) or alce.isOffsetlike(optional_offsetItems), 'alce.mono.T.List.new(): invalid argument: optional_offsetItems')
        assert((not optional_offsetSize) or alce.isOffsetlike(optional_offsetSize), 'alce.mono.T.List.new(): invalid argument: optional_offsetSize')
        local instance = {
            baseAddress = baseAddress,
            indexFrom = optional_indexFrom or self.indexFrom,
            indexBy = optional_indexBy or self.indexBy,
            offset = {
                items = optional_offsetItems or self.offset.items,
                size = optional_offsetSize or self.offset.size
            }
        }
        setmetatable(instance, { __index = self, __call = self.at })
        return instance
    end,

    --- Convenience constructor that returns new T.List that aliases the result from `readPointerChain(...)`
    newFromChain = function(self, ...) --> the newly created T.List
        return self:new(alce.readPointerChain(...))
    end,

    size = function(self) --> the number of items
        assert(alce.isAddresslike(self.baseAddress), 'alce.mono.T.List.size(): invalid state: baseAddress: ' .. tostring(self.baseAddress))
        return readInteger(self.baseAddress + self.offset.size)
    end,

    atUnsafe = function(self,index) --> address of the Nth element at index (starting from zero)
        local itemBase = readPointer(self.baseAddress + self.offset.items)
        return readPointer(itemBase + self.indexFrom + (index * self.indexBy))
    end,

    at = function(self, index) --> address of the Nth element at index (starting from zero)
        assert(alce.isAddresslike(self.baseAddress), 'alce.mono.T.List.at(): invalid state: baseAddress: ' .. tostring(self.baseAddress))
        assert(alce.isNonNegativeInteger(index), 'alce.mono.T.List.at(): invalid argument: index: ' .. tostring(index))
        assert(index < self:size(), 'alce.mono.T.List.at(): invalid argument: index is out of bounds')
        return self:atUnsafe(index)
    end,

    --[[{
        Returns an iterator which returns the value of the list item from optional_start to optional_end.
        Arguments will default to, or must be within the range of: [0,size) respectively.
    --}]]
    iterator = function(self, optional_start, optional_end) --> function-->counter,address: counts from 1; equivalent index is count-1
        local i = optional_start or 0
        local size = self:size()
        local e = optional_end or size
        assert(alce.isOffsetlike(i), 'alce.mono.T.List.iterator(): invalid argument: optional_start: ' .. tostring(optional_start))
        assert(alce.isOffsetlike(e), 'alce.mono.T.List.iterator(): invalid argument: optional_end: ' .. tostring(optional_end))
        assert(e <= size, 'alce.mono.T.List.iterator(): invalid argument: optional_end was out of bounds: ' .. tostring(optional_end))
        local info = debug.getinfo(2, "Sl")
        return function()
            if i < e then
                assert(i < self:size(), 'line ' .. tostring(info.currentline) .. ': alce.mono.T.List.iterator(): iterator went out of bounds during iteration... Size changed?')
                i = i + 1
                return i,self:atUnsafe(i-1)
            end
        end
    end,

    --- Convenience method wraps the result of the iterator in `alceClass:instance`, returning object instance aliases rather than addresses
    instanceIterator = function(self, alceClass, optional_start, optional_end) --> function-->count,ObjectAlias
        assert(alce.isCallable(alceClass.instance), 'alce.mono.T.List.instanceIterator(): invalid argument: alceClass must have an Instance method.')
        local iter = self:iterator(optional_start, optional_end)
        return function()
            local i,r = iter()
            if r then return i,alceClass:instance(r)
            else return nil end
        end
    end
}

--- Helper that asserts the process is attached and tries to launch the mono data collector if it's not connected already.
function alce.mono.init()
    assert(alce.isAttached(), 'alce.mono.init(): not attached to process')
    if (monopipe == nil) then assert(LaunchMonoDataCollector(), 'alce.mono.init(): LaunchMonoDataCollector() failed.') end
end

--- A representation of, and call-abstraction for, mono methods.
alce.mono.Method = {
    init = function(self, methodID, name, flags) --> self
        assert(alce.isPositiveInteger(methodID), 'alce.mono.Method.init(): invalid methodID')
        self.id = methodID
        self.flags = flags or mono_method_getFlags(methodID)
        for k,v in pairs(mono_method_get_parameters(methodID)) do self[k] = v end
        self.signature = alce.mono.method_getSignature(methodID, name)
        self.name = name
        return self
    end,

    new = function(self, methodID, name, flags) --> the newly created Method
        local instance = {}
        setmetatable(instance, { __index = self, __call = self.call })
        if methodID then instance:init(methodID, name, flags) end
        return instance
    end,

    isStatic = function(self) --> boolean
        return alce.hasFlag(METHOD_ATTRIBUTE_STATIC, self.flags)
    end,

    getAttributes = function(self) --> array of strings: the names of global `monoscript.lua` constants representing the various method attributes
        local t = {}
        for _,flagName in pairs(alce.monoscript.methodAttribute.names) do if alce.hasFlag(_G[flagName], self.flags) then table.insert(t, flagName) end end
        return t
    end,

    compile = function(self) --> address
        if not self.address then
            assert(alce.isPositiveInteger(self.id), 'alce.mono.Method.compile(): malformed method; not initialized?')
            local r=mono_compile_method(self.id)
            assert(alce.isAddresslike(r), 'alce.mono.Method.compile(): failed to compile method; returned: ' .. alce.fmt.address(self.address))
            self.address = r
        end
        return self.address
    end,

    --[[{
        Invokes the method. The method must already be compiled. `maybe_instance` can be nil if the method is static. `maybe_args` can be nil if the method takes no arguments. Arguments must be supplied in CE's invoke format: `{ {type=vt,value=v}, ... }`
    --}]]
    callUnsafe = function(self, maybe_instance, maybe_args) --> the results of `alce.mono.invoke`: value of type `self.returntype`, error, `vtype`
        if alce.cfg.debug_print then alce.debug(string.format("alce.mono.Method.callUnsafe(): attempting to invoke call '%s' on instance %s with...\n%s", self.signature.full, alce.fmt.address(maybe_instance), alce.fmt.table({wants=self.parameters, giving=maybe_args or 'Nothing'}))) end
        return alce.mono.invoke(self.id, maybe_instance, maybe_args, self.parameters, self.flags)
    end,

    --[[{
        Invokes the method after safety checks and argument processing. `maybe_instance` can be nil if the method is static. `maybe_args` can be nil if the method takes no arguments.

        Arguments may be provided positionally in the form of either an arbitrary value or as a pair table matching CE's argumment format: `{type=vt,value=v}`. The types of raw value arguments are guessed from the method's corresponding parameter type.

        > **Caution:** doesn't type-check the provided arguments; it only deduces types from the method's parameters.

        Example usage:
        ```lua
        local e = FlagEnumValues.const -- an alce.Class
        local t = alce.T[vtDword] -- so we dont need to type `{type=vtDword,value=...}`
        local SetPlayerFlag = alce.mono.Method( ... ) -- void Player:SetPlayerFlag(enum,bool)
        SetPlayerFlag:call(player_ptr, t(e.hasGodmode), true)
        SetPlayerFlag:call(player_ptr, t(e.isCheating), false)
        ```
    --}]]
    call = function(self, maybe_instance, ...) --> self.returntype, error, vtype
        assert(self.id and self.parameters, 'alce.mono.Method.call(): malformed method; not initialized?')
        local raw_args = {...}
        local pcount = #raw_args
        assert(pcount == #(self.parameters), 'alce.mono.Method.call(): called with the wrong number of parameters')
        assert(self:isStatic() or alce.isAddresslike(maybe_instance), 'alce.mono.Method.call(): non-static method was called without an instance')
        self:compile()
        local args = {}
        for i=1, pcount do
            local arg = raw_args[i]
            assert(arg ~= nil, 'alce.mono.Method.call(): argument ' .. tostring(i) .. ' was nil... Did you mean `0` or `false`?')
            if type(arg) == 'table' then
                assert(arg.type and alce.T[arg.type] and arg.value~=nil, 'alce.mono.Method.call(): argument ' .. tostring(i) .. ' was a malformed table; tables must be {type=,value=}')
                args[i] = arg
            else
                -- best-effort: the user can pass the type explicitly if we get it wrong
                args[i] = alce.T.fromMono(self.parameters[i].type)(arg)
            end
        end

        local result, exception, vtype = self:callUnsafe(maybe_instance, args)
        assert(not exception, 'alce.mono.Method.call(): exception: ' .. tostring(exception))
        return result
    end,
}

--[[{
    a representation of a mono class type which will fetch, sort, and process its methods and fields into appropriate subtables.

    > TODO: might be worth-while to limit parent fetching to stop at `UnityEngine` stuff just to cut down on junk... Ain't nobody using `m_CancellationTokenSource`
--}]]
alce.mono.Class = {
    new = function(self, assemblyNameOrImage, className, optional_namespace, optional_getParents) --> the newly created Class
        alce.debug('alce.mono.Class.new(): attempting to get "', className, optional_getParents and '" with parents' or '"')
        assert(alce.isNonBlankString(className), 'alce.mono.Class.new(): invalid argument: className is nil')
        assert(alce.isPositiveInteger(assemblyNameOrImage) or alce.isNonBlankString(assemblyNameOrImage), 'alce.mono.Class.new(): invalid argument: assemblyNameOrImage: ' .. tostring(assemblyNameOrImage))
        assert(optional_namespace == nil or type(optional_namespace) == 'string', 'alce.mono.Class.new(): invalid argument: optional_namespace: ' .. tostring(optional_namespace))
        local id = alce.mono.getClass(assemblyNameOrImage, className, optional_namespace)
        if not alce.isAddresslike(id) then
            alce.warn('alce.mono.Class.new(): failed to find class: ' .. tostring(className))
            return nil
        end
        local hierarchy = alce.mono.class_getParentHierarchy(id)
        local methods = alce.mono.getProcessedMethods(id, optional_getParents, hierarchy, true)
        if not methods then
            alce.warn('alce.mono.Class.new(): failed to get fields: ' .. tostring(className))
            return nil
        end
        local fields = alce.mono.getProcessedFields(id, optional_getParents, hierarchy, true)
        if not fields then
            alce.warn('alce.mono.Class.new(): failed to get fields: ' .. tostring(className))
            return nil
        end
        local instance = {
            id = id,
            namespace = optional_namespace,
            name = className,
            method = methods,
        }
        for k,v in pairs(fields) do instance[k] = v end
        setmetatable(instance, { __index = self })
        return instance
    end,

    instance = function(self, baseAddress) --> ObjectAlias: a factory that returns a frieldy ergonomic wrapper around an instance of this monoclass
        return alce.mono.ObjectAlias(self, baseAddress)
    end,

    --- convenient shorthand for self:instance(alce.safeChain(...))
    instanceFrom = function(self, ...) --> ObjectAlias
        return self:instance(alce.safeChain(...))
    end,
}

local function aliasRead(context, key)
    local class = context.type
    local offset = class.offset[key]
    if offset then
        assert(alce.isNonEmptyTable(class.meta), 'alce.mono.ObjectAlias(): error in aliasRead: metadata table for "' .. tostring(class.name) .. '" was invalid; not populated?')
        local meta = class.meta.offset[key]
        assert(meta, 'alce.mono.ObjectAlias(): error in aliasRead: failed to find metadata for offset ' .. tostring(key))
        local t = alce.T.fromMono(meta.monotype)
        return t:read(context.baseAddress + offset)
    end
    local const = class.const[key]
    if const then return const end
    local static = class.static[key]
    if static and alce.isAddresslike(a) then readPointer(a) end
    assert(false, 'alce.mono.ObjectAlias(): error in aliasRead: failed to find datamember ' .. tostring(key))
end

local function aliasWrite(context, key, value)
    local class = context.type
    local offset = class.offset[key]
    if offset then
        assert(alce.isNonEmptyTable(class.meta), 'alce.mono.ObjectAlias(): error in aliasWrite: metadata table for "' .. tostring(class.name) .. '" was invalid; not populated?')
        local meta = class.meta.offset[key]
        assert(meta, 'alce.mono.ObjectAlias(): error in aliasWrite: failed to find metadata for offset ' .. tostring(key))
        local t = alce.T.fromMono(meta.monotype)
        return t:write(context.baseAddress + offset, value)
    end
    assert(not class.const[key], "alce.mono.ObjectAlias(): error in aliasWrite: can't write to constant value: " .. tostring(key))
    assert(not class.static[key], "alce.mono.ObjectAlias(): error in aliasWrite: shouldn't write to static member: " .. tostring(key) .. ". Did you really intend to? You can try doing it manually.")
    assert(false, 'alce.mono.ObjectAlias(): error in aliasWrite: failed to find datamember ' .. tostring(key))
end

--[[{
    ObjectAlias is an ergonomic wrapper around a monoclass object instance that lets you
    call methods or read and write from member variables in a natural way.

    ```lua
    local obj = ObjectAlias(theClassType, addrOfClassInstance)
    print(obj.x) -- read from datafield 'x'
    obj.x = 3 -- write to datafield 'x'
    assert(obj['x'] == 3) -- read from datafield 'x' again
    obj.SimpleMethod('my string') -- invoke a non-static method and provide it a string
    obj['OverloadedMethod(single)'](3.1415) -- invoke an overloaded non-static method and provide it a float value
    ```

    The datatypes used during read, write, call operations are interpretted from the metadata
    stored in the alce.mono.Class object. alce.mono.Class is a representation of the mono class
    type, while the alce.mono.ObjectAlias can represent an instance of said type.

    alce.mono.Class provides an ObjectAlias factory which can be called like: `obj = myAlceClassTable.Player:Instance(addr)`
--}]]
function alce.mono.ObjectAlias(alceClass, baseAddress) --> proxy object
    assert(alce.isAddresslike(baseAddress), 'alce.mono.ObjectAlias(): invalid argument: baseAddress: ' .. tostring(baseAddress))
    local internal = {
        baseAddress = baseAddress,
        type = alceClass,
    }
    local proxy = {} -- empty forever; everything happens in the closure and metatable
    setmetatable(proxy, {
        __tostring = function() return string.format("%s@%s", alceClass.name, alce.fmt.address(internal.baseAddress)) end,
        __pairs = function(_) error("alce.mono.ObjectAlias.__pairs(): Aliases don't support iteration; not sure what behavior was expected. Perhaps you want the alce.mono.Class; try `.__type`?") end,

        __eq = function(a, b)
            local ameta = getmetatable(a)
            local bmeta = getmetatable(b)
            return ameta == bmeta and rawequal(ameta.__index, bmeta.__index) and a.__baseAddress == b.__baseAddress
        end,

        -- __index handles all the regular `obj.thing` / `obj[thing]` accesses if the key isnt found
        __index = function(tbl, key)
            if not alce.isNonBlankString(key) then
                alce.warn('alce.mono.ObjectAlias.__index(): invalid argument: key should be the name of a data-member or method. Got: ' .. tostring(key))
                return nil
            end
            local m = internal.type.method[key]
            if m then
                return function(optional_self, ...) -- self is unnecessary: workaround to allow both `:` and `.` calling
                    if optional_self == tbl then return m:call(internal.baseAddress, ...)
                    else return m:call(internal.baseAddress, optional_self, ...) end
                end
            elseif key:sub(1, 2) == "__" then return internal[key:sub(3)]
            else return aliasRead(internal, key) end
        end,

        -- __newindex handles all the assignments to new keys e.g. `obj.x = 3` (always triggers because `proxy` is empty)
        __newindex = function (_, key, value) return aliasWrite(internal, key, value) end
    })
    return proxy
end

--- a table that loads and holds the mono clases you specify, associated by name, in the form of `alce.mono.Class`
alce.mono.ClassTable = {
    new = function(self, optional_keyPrefixAssembly, optional_keyPrefixNamespace) --> the newly created ClassTable
        local instance = { _internal = {
            targetList = {},
            isLoaded = false,
            keyPrefixAssembly = optional_keyPrefixAssembly,
            keyPrefixNamespace = optional_keyPrefixNamespace,
        } }
        setmetatable(instance, { __index = self })
        return instance
    end,

    --- accepts explicit `add({ {image, class[, namespace]}, ... })`
    add = function(self, ...) --> self
        assert(not self._internal.isLoaded, 'alce.mono.ClassTable.add(): cannot add while table is loaded. Try calling unload() first?')
        local entries = {...}
        alce.debug('alce.mono.ClassTable.add(): added targets: ' .. alce.fmt.table(entries))
        for _, entry in ipairs(entries) do table.insert(self._internal.targetList, entry) end
        return self
    end,

    --- convenience abstraction: `addFromImage(image, (class | {class, namespace}), ...)`
    addFromImage = function(self, image, ...) --> self
        assert(not self._internal.isLoaded, 'alce.mono.ClassTable.add(): cannot add while table is loaded. Try calling unload() first?')
        local args = {...}
        for _, item in ipairs(args) do
            if type(item) == 'table' then table.insert(self._internal.targetList, {image, item[1], item[2]})
            else table.insert(self._internal.targetList, {image, item, nil})
            end
        end
        return self
    end,

    isLoaded = function(self) --> boolean
        return self._internal.isLoaded == true
    end,

    load = function(self, optional_getParents) --> self
        alce.debug('alce.mono.ClassTable.load(): called.')
        assert(not self:isLoaded(), 'alce.mono.ClassTable.load(): already loaded. Forget to call :unload()?')
        self._internal.isLoaded = true
        local assemblies = mono_enumAssemblies()
        local images = {}
        local r = {}
        for _,target in ipairs(self._internal.targetList) do
            local assemblyNameOrImage, className, namespace = unpack(target)
            local assemblyName = type(assemblyNameOrImage) == 'string' and assemblyNameOrImage or mono_image_get_name(assemblyNameOrImage)
            if not assemblies[assemblyName] then
                assemblies[assemblyName] = alce.mono.getImage(assemblyName, assemblies)
            end
            local c = alce.mono.Class:new(assemblies[assemblyName], className, namespace, optional_getParents)
            if c then
                local keyPrefixA = self._internal.keyPrefixAssembly and assemblyName .. '.' or ''
                local keyPrefixB = self._internal.keyPrefixNamespace and c.namespace .. '.' or ''
                local key = keyPrefixA .. keyPrefixB .. className
                if r[key] then alce.warn('alce.mono.ClassTable.load(): Overwriting duplicate key: "' .. key .. '" (try enabling assembly or namespace prefixing?)') end
                r[key] = c
            end
        end
        for k,v in pairs(r) do self[k] = v end
        return self
    end,

    loadWithParents = function(self) return self:load(true) end,

    unload = function(self) --> self
        alce.debug('alce.mono.ClassTable.unload(): called.')
        if not self:isLoaded() then alce.warn('alce.mono.ClassTable.unload() called but nothing was loaded?... Doing it anyways.') end
        local internal = self._internal
        local count = #self
        for i=0, count do self[i]=nil end
        self._internal = internal
        self._internal.isLoaded = false
        return self
    end,

    clear = function(self) --> self
        alce.debug('alce.mono.ClassTable.clear(): called.')
        if self:isLoaded() then self:unload() end
        self._internal.targetList = {}
        return self
    end,
}
---------------------------
----/> Mono Features ------
---------------------------



--------------------------------
-----< Cheat Table Features ----
---------------------------------
--- # helpers for common manipulations of the cheat table

function onMemRecPreExecute(memrec, newState)
    if memrec.Type == vtAutoAssembler then
        alce.debug('Trying to run script: ', memrec.Description)
        --- The MemoryRecord of the the script currently executing. Only be valid during the time an enable/disable script is being run from the cheat table: it's invalid during syntax check and running via the 'execute' button .
        alce.THIS = memrec
    end
end

function onMemRecPostExecute(memrec, newState, succeeded)
    alce.THIS = nil
    alce.debug('Script ', memrec.Description, succeeded and ' succeeded' or ' failed')
    if memrec.Type == vtAutoAssembler then
        if succeeded then
            --- The MemoryRecord of the last script to succeed execution. Only valid after a table script has successfully run. Doesn't count scripts run from the 'execute' button.
            alce.LAST_SUCCESS = memrec
        else
            --- The memoryRecord of the last script to fail execution. Only valid after a table script has failed to run. Doesn't count scripts run from the 'execute' button.
            alce.LAST_FAILURE = memrec
        end
    end
    if alce.isCallable(alce.executionCallback) then
        alce.executionCallback(memrec, newState, succeeded)
        alce.executionCallback = nil
    end
end

alce.cheattable = {}

--- Makes disableWithoutExecute() be called on the next MemoryRecord script that runs successfully. Can be used at the bottom of an [ENABLE] section to turn a script into a momentary button rather than toggle.
function alce.cheattable.disableAfterSuccess(optional_disableBeep)
    alce.executionCallback = function(this,_,succeeded)
        if succeeded then
            this:disableWithoutExecute()
            if not optional_disableBeep then beep() end
        end
    end
end

--- `destroy()`'s  all children of the given memoryRecord
function alce.cheattable.clearChildren(memoryRecord)
  local count = memoryRecord.Count
  for i = count-1, 0, -1 do memoryRecord.Child[i].destroy() end
end

--- finds the MR by description then calls `alce.cheattable.clearChildren`
function alce.cheattable.clearChildrenByDesc(desc, optional_addressList)
    local al = optional_addressList or getAddressList()
    local parent = al.getMemoryRecordByDescription(desc)
    if parent then alce.cheattable.clearChildren(parent) end
end

--[[{
    Creates a new MemoryRecord and attaches it to `parent`. `optional_address` may be an integer or a string. `optional_offsets` may be an array of integer offsets from `address` such as `{ 0x10, ... }`. `optional_saveToTable` may be a boolean; children created from this function aren't saved by default.

    `optional_dropDownSettings` is a dict which if not nil must at minimum contain an either an `optionsFrom` string containing the description string from another dropdown MR, or an `options` string formatted as newline-separated pairs e.g. `"value:desc\n..."`. You may optionally provide `noManualInput` `hideNumbers`, and `dontDisplayAsString` booleans.

    Example usage, creating a pointer+offsets MR with a dropdown menu:
    ```lua
    local ddsettings = {
        options = '0:disabled\n1:normal\n2:overclocked',
        --optionsFrom = "some other MR description", -- if we already set one up and didn't want to duplicate...
        noManualInput = true,
        hideNumbers = true,
        --dontDisplayAsString = false -- displays MR value as dropdown string by default
    }
    local newmr = alce.cheattable.createChild(alce.THIS, 'mode', vtByte, baseaddr, {stateOffset, modeOffset}, false, ddsettings)
    print('the address of mode is ' .. newmr.AddressString)
    ```
--}]]
function alce.cheattable.createRecord(optional_parent, optional_description, optional_vtype, optional_address, optional_offsets, optional_dropDownSettings, optional_saveToTable) --> the newly created MemoryRecord
    local mr = AddressList.createMemoryRecord()
    if alce.isNonBlankString(optional_description) then mr.Description = optional_description end
    mr.Type = optional_vtype or vtDword
    mr.DontSave = optional_saveToTable ~= true
    if alce.isAddresslike(optional_address) then mr.Address = string.format("%X", optional_address)
    elseif alce.isNonBlankString(optional_address) then mr.Address = optional_address
    else assert(optional_address == nil, 'alce.cheattable.createChild(): invalid argument: optional_address must be nil, a valid address integer, or a non-blank string') end
    if optional_offsets then
        assert(type(optional_offsets) == 'table', 'alce.cheattable.createChild(): invalid argument:  optional_offsets must be an array or `nil`')
        mr.OffsetCount = #optional_offsets
        for i,offset in ipairs(optional_offsets) do mr.Offset[i - 1] = offset end
    end
    if optional_dropDownSettings then
        assert(type(optional_dropDownSettings) == 'table', 'alce.cheattable.createChild(): invalid argument: optional_dropDownSettings must be a dict or `nil`')
        if alce.isNonBlankString(optional_dropDownSettings.options) then mr.DropDownList.Text = optional_dropDownSettings.options
        elseif alce.isNonBlankString(optional_dropDownSettings.optionsFrom) then mr.DropDownLinkedMemrec = optional_dropDownSettings.optionsFrom
        else assert(false, 'alce.cheattable.createChild(): invalid argument: dropDown table requires either `options` or `optionsFrom` be a non-blank string') end
        mr.DropDownDescriptionOnly = optional_dropDownSettings.hideNumbers == true
        mr.DropDownReadOnly = optional_dropDownSettings.noManualInput == true
        mr.DisplayAsDropDownListItem = optional_dropDownSettings.dontDisplayAsString ~= true
    end
    mr.Options='[moAllowManualCollapseAndExpand]'
    if optional_parent then mr.appendToEntry(optional_parent) end
    return mr
end

function alce.cheattable.createHeader(optional_parent, optional_description, optional_showCollapseButtons, optional_saveToTable) --> the newly created MemoryRecord
    local mr = AddressList.createMemoryRecord()
    if alce.isNonBlankString(optional_description) then mr.Description = optional_description end
    if optional_parent then mr.appendToEntry(optional_parent) end
    mr.DontSave = optional_saveToTable ~= true
    mr.IsGroupHeader = true
    mr.Options= optional_showCollapseButtons and '[moHideChildren,moAllowManualCollapseAndExpand,moManualExpandCollapse]' or '[moHideChildren,moAllowManualCollapseAndExpand]'
    return mr
end
----------------------------------
----/> Cheat Table Features ------
----------------------------------


